name: release

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  release:
    runs-on: [self-hosted, arma-tools]
    steps:
      - name: Make mission pbo
        uses: team-gsri/actions-arma-tools/release-mission@v0
        with:
          missionName: Scorpion
          source: ./CONT_Scorpion.Malden
